name: Continuous Integration (PR)
on:
  pull_request:
    # run CI on pull requests to master or a release branch
    branches:
      - master
      - 'release/**'
      - 'releases/**'
      - 'feat/precompile'
# run default ci checks against current PR
jobs:
  default:
    uses: ./.github/workflows/ci-default.yml
  rocksdb:
    uses: ./.github/workflows/ci-rocksdb-build.yml
  precompile:
    uses: ./.github/workflows/ci-precompile.yml
  post-pipeline-metrics:
    uses: ./.github/workflows/metric-pipeline.yml
    if: always() # always run so we metric failures and successes
    with:
      aws-region: us-east-1
      metric-name: kava.releases.pr
      namespace: Kava/ContinuousIntegration
    secrets: inherit
    needs: [default]
